server:
  port: 8107
  shutdown: graceful

spring:
  application:
    name: job-admin
  profiles:
    active: prod
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://mysql:3306/al_job?useSSL=false&charsetEncoding=utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      pool-name: Job_Admin_DB_Pool
      minimum-idle: 1
      idle-timeout: 600000
      maximum-pool-size: 4
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: /data/logs/${spring.application.name}.log
  charset:
    file: UTF-8
    console: UTF-8
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 64MB

al-job:
  url: http://job-admin:8107
